### ISSUE TITLE
FYI: Video mentioning this template is available

### ISSUE THREAD

**Issue by LegalizeAdulthood** [lukka/CppCMakeVcpkgTemplate#14]
Hi,

I just did a presentation on Using GitHub Actions for Continuous Integration last night for Utah C++ Programmers.  I uploaded the video to YouTube and show how to use your template workflow at the end of the video.  (The first part of the video is explaining the github action framework and how to set things up manually.)

Video: https://www.youtube.com/watch?v=1q8BQtvr8sY

**Comment by lukka** [comment]
@LegalizeAdulthood the video is a great explanation about GH actions and CMake+vcpkg+ninja all round, well done! 
Regarding the place where the `vcpkg binary caching`'s artifacts are being restored from the GHA Cache, it happens whenever vcpkg is being run, which in this template happens when CMake configures the source tree and writes the "build files" into the build directory. You can see the list of restored packages [here](https://github.com/LegalizeAdulthood/trn-actions/actions/runs/5537366598/jobs/10106109963#step:5:98).
